# PRACTICE PROBLEMS ON FUNCTION


**<font color='red'>[MUST MAINTAIN VARIABLE NAMING CONVENTIONS FOR ALL THE TASKS]</font>**
**<font color='red'>[Solve all the tasks sequentially]</font>**


In [ ]:
#Msi sir function practice 
#01 

def ascii_val_count(str1):
    ascii=''
    list1=[]
    for i in range(len(str1)):
        num=ord(str1[i])
        ascii=str(num)+str1[i]+str(num)
        list1.append(ascii)
    return list1

str1="pythonbook"
val=ascii_val_count(str1)
print(val)

In [1]:
#Msi sir function practice 
#02

def positive_negative_index(str1):
    j=-10
    dict_1={}
    for i in range(len(str1)):
        num=j+i
        # print(str1[num],num,i)
        if str1[i] not in dict_1:
            dict_1[str1[i]]=[i]
            dict_1[str1[i]].append(num)
        elif str1[i] in dict_1:
            # dict_1[str1[i]] = [i]
            dict_1[str1[i]].append(i)
            dict_1[str1[i]].append(num)
    return dict_1
str1="pythonbook"
dict_2=positive_negative_index(str1)
print(dict_2)

{'p': [0, -10], 'y': [1, -9], 't': [2, -8], 'h': [3, -7], 'o': [4, -6, 7, -3, 8, -2], 'n': [5, -5], 'b': [6, -4], 'k': [9, -1]}


In [2]:
#Msi sir function practice 
#03

def ascending_dict(str2):


    str1=str2.split(" ")

    dict_1={}
    for i in range(len(str1)):

        # print(str1[num],num,i)
        if str1[i] not in dict_1:
            dict_1[str1[i]]=1
        elif str1[i] in dict_1:
            # dict_1[str1[i]] = [i]
            dict_1[str1[i]]+=1
    list_val=[]
    list_key=[]
    for key,val in dict_1.items():
        list_val.append(val)
        list_key.append(key)
        for i in range(len(list_val)-1):

            for j in range(i+1,len(list_val)):
                if list_val[i]>list_val[j]:
                    list_val[i],list_val[j]=list_val[j],list_val[i]
                    list_key[i],list_key[j]=list_key[j],list_key[i]
    dict_2={}
    for i in range(len(list_key)):
        dict_2[list_key[i]]=list_val[i]
    return  dict_2
str2="go there come and go here and there go care"
val=ascending_dict(str2)
print(val)

{'come': 1, 'here': 1, 'care': 1, 'there': 2, 'and': 2, 'go': 3}


In [1]:
def prime_number(str1):
    for i in range(len(str1)):
        val = int(str1[i])
        counter=0
        for x in range(1, val + 1):
            if val % x == 0:
                counter += 1
        if counter == 2:
            return "prime number"
        else:
            return "Not prime number"
str1 = "2441396"
prime_number(str1)
def perfect_number(str1):
    for i in range(len(str1)):
        val = int(str1[i])
        sum = 0
        for x in range(1, val):
            if val % x == 0:
                sum += x
                print(sum)
        if sum == val:
            return "perfect number"
        else:
            return "Not perfect number"
str1 = "2441396"
perfect_number(str1)
def even_odd_check(str1):
    for i in range(len(str1)):
        val = int(str1[i])

        if val % 2 == 0:
            return "even number"
        else:
            return "odd number"
str1 = "2441396"
even_odd_check(str1)
even=even_odd_check(str1)
prime=prime_number(str1)
perfect=perfect_number(str1)
temp=(even,prime,perfect)
print(temp)

1
1
('even number', 'prime number', 'Not perfect number')


In [1]:

def even_prime_perfect(str1):
    ans={}
    for i in range(len(str1)):
        val = int(str1[i])
        even=even_odd_check(val)
        prime=prime_number(val)
        perfect=perfect_number(val)
        temp=(even,prime,perfect)
        if val not in ans:
            ans[val]=temp
        
    return ans
def prime_number(val):
#     for i in range(len(str1)):
#         val = int(str1[i])
        counter=0
        for x in range(1, val + 1):
            if val % x == 0:
                counter += 1
        if counter == 2:
            return "prime number"
        else:
            return "Not prime number"
    
def perfect_number(val):
#     for i in range(len(str1)):
#         val = int(str1[i])
        sum = 0
        for x in range(1, val):
            if val % x == 0:
                sum += x
                print(sum)
        if sum == val:
            return "perfect number"
        else:
            return "Not perfect number"    
def even_odd_check(val):
#     for i in range(len(str1)):
#         val = int(str1[i])

        if val % 2 == 0:
            return "even number"
        else:
            return "odd number"
    
    
str1 = "2441396"
val1=even_prime_perfect(str1)
print(val1)
    

1
1
3
1
3
1
1
4
1
3
6
{2: ('even number', 'prime number', 'Not perfect number'), 4: ('even number', 'Not prime number', 'Not perfect number'), 1: ('odd number', 'Not prime number', 'Not perfect number'), 3: ('odd number', 'prime number', 'Not perfect number'), 9: ('odd number', 'Not prime number', 'Not perfect number'), 6: ('even number', 'Not prime number', 'perfect number')}


In [8]:
matrix_A = [ [1,5], [-4,3]]
matrix_B = [ [2,-1] , [4,-1] ]


main_list=[]

for j in range(len(matrix_A)):
    mat_a=[]
    for i in range(len(matrix_A[j])):

        sum=matrix_A[j][i]+matrix_B[j][i]
        mat_a.append(sum)
    main_list.append(mat_a)
    
    
print(main_list)
        
        
        

[[3, 4], [0, 2]]


In [10]:
def matrix_list(matrix):
    for i in matrix:
        for j in i:
            print(j,end=" ")
        print()
    
matrix= [[1,3,2, 4], [4, 5, 6, 7], [7, 8, 9, 3], [9, 1, 2, 3]]
matrix_list(matrix)



1 3 2 4 
4 5 6 7 
7 8 9 3 
9 1 2 3 


In [9]:
def convert_to_diagonal(square_matrix_dict):
    list1=[]
    for key,val in square_matrix_dict.items():
        # print("Non-diagonal matrix:")
        # print("In list of list format: ",[val])
        list1.append(val)
    print("Non-diagonal matrix:")
    print("In list of list format: ",list1)
    for val in list1:
        for i in val:
            
                print(i,end=" ")
        print()
    print()
    print(list1)
    list2=[]
    for count in range(len(list1)):
        print(list1[count])
        for i in range(len(list1[count])):
            
            if i==count:
                pass
            else:
                list1[count][i]=0
    print(list1)
square_matrix_dict = {1: [1, 2, 3, 4], 2: [4, 5, 6, 7], 3: [7, 8, 9, 3], 4: [9, 1, 2, 3]}
convert_to_diagonal(square_matrix_dict)

Non-diagonal matrix:
In list of list format:  [[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 3], [9, 1, 2, 3]]
1 2 3 4 
4 5 6 7 
7 8 9 3 
9 1 2 3 

[[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 3], [9, 1, 2, 3]]
[1, 2, 3, 4]
[4, 5, 6, 7]
[7, 8, 9, 3]
[9, 1, 2, 3]
[[1, 0, 0, 0], [0, 5, 0, 0], [0, 0, 9, 0], [0, 0, 0, 3]]


### Task 1
Write a function called **check_awesomeness** that takes a number as an argument and Checks whether the number is Awesome or not. If the number is Awesome, it returns True. Otherwise False.
 
**Awesome number:** a number where every digit is less than its immediate left digit is called an Awesome number. A single digit number cannot be a awesome number(e.g. 5421 is an Awesome number).

==========================================================

**Function Call1:**\
check_awesomeness(976321)\
**Output1:**\
True

==========================================================

**Function Call2:**\
check_awesomeness(9766321)\
**Output2:**\
False

==========================================================

**Function Call3:**\
check_awesomeness(9)\
**Output3:**\
False

==========================================================

**Function Call4:**\
check_awesomeness(78)\
**Output4:**\
False

==========================================================

**Function Call5:**\
check_awesomeness(87)\
**Output4:**\
True

In [18]:
#todo

def check_awesomeness(number):
    count=0
    #flag= True
    num=str(number)
    for i in range(len(num)-1):
        if int(num[i])>int(num[i+1]):
            pass
        else:
            count+=1
            #flag = False
    if count>=1:
        return False
    else:
        return True
    
number=int(input("Enter the number: "))
print(check_awesomeness(number))


Enter the number: 976321
True


### Task 2
Write a function called **check_awesome** that takes a list of numbers(integer) as an argument and Prints whether the number is Awesome or not.

**<font color='red'>Must reuse the check_awesomeness() function.</font>**

==========================================================

**Function Call1:**\
check_awesome([976321, 321, 9763221, 9742, 876, 3211])\
**Output1:**\
976321 is an awesome number.\
321 is a awesome number.\
9763221 is a not-so-awesome number.\
9742 is an awesome number.\
876 is an awesome number.\
3211 is a not-so-awesome number.

==========================================================

**Function Call2:**\
check_awesome([97821, 97210, 979210])\
**Output2:**\
97821 is a not-so-awesome number.\
97210 is an awesome number.\
979210 is a not-so-awesome number.

In [22]:
#todo
def check_awesome(list1):
    for i in range(len(list1)):
        var1=check_awesomeness(list1[i])
        if var1==True:
            print(list1[i],"is an awesome number.")
        else:
            print(list1[i],"is a not-so-awesome number.")
#         str1=str(list1[i])
#         for j in range(1,len(str1)):
            
#             if int(str1[j])<int(str1[j-1]):
#                 print("is an awesome number.")
#             else:
#                 print("is no an awesome number.")
list1=[976321, 321, 9763221, 9742, 876, 3211]
check_awesome(list1)

976321 is an awesome number.
321 is an awesome number.
9763221 is a not-so-awesome number.
9742 is an awesome number.
876 is an awesome number.
3211 is a not-so-awesome number.


### Task 3
Write a function called **find_max_min** that takes a list of numbers(integers) as a  function parameter and finds the numbers with maximum and minimum value. Then returns these two numbers as a **tuple** and prints the results using tuple unpacking in the function call accorrding to the given format. Both valid and invalid numbers should be considered for finding maximum and minimum.<font color='red'>[Must use tuple packing & unpacking] </font> 

==========================================================

**Function Call1:**\
find_max_min([976321, 321, 9763221, 9742, 876, 3211, 976321, 9742])\
**Output1:**\
Returned value from find_max_min() is: (9763221, 321)\
Number with maximum value is 9763221\
Number with minimum value is 321

==========================================================

**Function Call2:**\
find_max_min([97821, 1, 97210, 963, 979210, 979210])\
**Output2:**\
Returned value from find_max_min() is: (979210, 1)\
Number with maximum value is 979210\
Number with minimum value is 1

In [42]:
#todo
def find_max_min(list1):
    max_val=None
    min_val=None
    for i in range(len(list1)):
        if max_val==None and min_val==None:
            min_val=list1[i]
            max_val=list1[i]
        else:
            if max_val<list1[i]:
                max_val=list1[i]
            elif min_val>list1[i]:
                min_val=list1[i]
    return max_val,min_val
                
                
    
list1=[976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]   
var1=find_max_min(list1)
val1,val2=var1
print("Returned value from find_max_min() is:",var1)
print("Number with maximum value is",val1)
print("Number with maximum value is",val2)


Returned value from find_max_min() is: (9763221, 321)
Number with maximum value is 9763221
Number with maximum value is 321


In [38]:
list1=[976321, 321, 9763221, 9742, 876, 3211, 976321, 9742] 

max_val=None
min_val=None
for i in range(len(list1)):
    if max_val==None and min_val==None:
        min_val=list1[i]
        max_val=list1[i]
    else:
        if max_val<list1[i]:
            max_val=list1[i]
        elif min_val>list1[i]:
            min_val=list1[i]
            
print(max_val)
print(min_val)
            

9763221
321


### Task 4
Write a function called **data_cleaning** that takes a string as an argument. Then gets the numbers from the given string and removes all extra spaces. Stores the clean numbers (integers) in a list and **returns** it to the function call.

==========================================================

**Function Call1:**\
data_cleaning("97821, 1 &nbsp;&nbsp;&nbsp;  , 97210,&nbsp;&nbsp; 963, &nbsp;&nbsp;&nbsp;979210 , 979210   ")\
**Output1:**\
Data after cleaning: [97821, 1, 97210, 963, 979210, 979210]

==========================================================

**Function Call2:**\
data_cleaning("976321, 321&nbsp;&nbsp;,&nbsp;&nbsp;&nbsp;9763221, &nbsp;&nbsp;&nbsp;9742, 876,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3211")\
**Output2:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211]

==========================================================

**Function Call3:**\
data_cleaning("976321, 321 ,&nbsp;&nbsp;&nbsp; 9763221, 9742, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;876, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3211, 976321&nbsp;&nbsp;&nbsp;&nbsp;, 9742")\
**Output3:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]

In [3]:
#todo
def data_cleaning(string1):
    string2=string1.split(",")
    list1=[]
    for i in range(len(string2)):
        a=string2[i].strip(" ")
        list1.append(int(a))
    return list1
    
string1="976321, 321  ,   9763221,    9742, 876,        3211"
print(data_cleaning(string1))

[976321, 321, 9763221, 9742, 876, 3211]


In [13]:
def data_cleaning(string1):
    list1=string1.split(",")
    str2=''
    str1=' '
    for i in range(len(list1)):
        if str(list1[i])==" ":
            pass
        else:
            str2+=list1[i]
    
    srt1=str2.split(" ")
    return str1
            
    
    
string1="976321, 321  ,   9763221,    9742, 876,        3211"
data_after_cleaning=data_cleaning(string1)
print(data_after_cleaning)

### Task 5
Write a function called **grouping_data** that takes  a list of numbers(integers) as a  function parameter and creates a dictionary where "valid", "invalid", and "duplicate" are the keys. The numbers that falls in those categories are the values.

**Valid & Invalid numbers:** A number with a minimum length of 4 and a maximum length of 6 is considered to be valid for this assignment. All the other numbers are considered to be Invalid numbers.\
**Duplicate numbers:** If a number appears more than once in the string, then that is a dupliacte number. Both valid and invalid numbers can be duplicates.

Lastly, print the dictionary **inside the function** and **return** the dictionary to the function call.

==========================================================

**Function Call1:**\
grouping_data([97821, 1, 97210, 963, 979210, 979210])\
**Output1:**\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
Valid number list obtained from the dictionary: [97821, 97210, 979210]


==========================================================

**Function Call2:**\
grouping_data([976321, 321, 9763221, 9742, 876, 3211])\
**Output2:**\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]


==========================================================

**Function Call3:**\
grouping_data([976321, 321, 9763221, 9742, 876, 3211, 976321, 9742])\
**Output3:**\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]



In [ ]:
#todo
list1=[97821, 1, 97210, 963, 979210,979210,1,1,1,1]
string1=''
list2=[]
list3=[]
list4=[]

duplicate=[]
dict_1={}
for i in range(len(list1)):

     if (len(str(list1[i])))>=4 and len(str(list1[i]))<=6:
         if list1[i] not in list2:
             list2.append(list1[i])
     else:
         if list1[i] not in list3:
            list3.append(list1[i])
for i in range(len(list2)):
    dict_1["valid"]=list2
for j in range(len(list3)):
    dict_1["unvalid"]=list3
# list1=[97821, 1, 97210, 963, 979210]


for i in list1:
    if i not in list4:
        list4.append(i)
for j in list4:
    counter=0
    for k in list1:
        if j==k:
            counter+=1
    if counter>=2:
        duplicate.append(j)

for i in duplicate:
    dict_1["duplicate"]=duplicate

print(dict_1)

### Task6
Write a function called **individual_line_data** that takes a string as an argument. This function should do the following. 
* clean and prints the data.
* group the numbers in a dictionary obtained from the given string.
* check whether the **valid numbers** are awesome or not.
* find and print the maximum and minimum number among the **valid numbers** obtained from the given string.

*Hints:*\
You MUST reuse data_cleaning(), grouping_data(), check_awesome() and find_max_min() functions. 

==========================================================

**Function Call1:**\
individual_line_data("97821, 1 &nbsp;&nbsp;&nbsp;  , 97210,&nbsp;&nbsp; 963, &nbsp;&nbsp;&nbsp;979210 , 979210   ")\
**Output1:**\
Data after cleaning: [97821, 1, 97210, 963, 979210, 979210]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
Valid number list obtained from the dictionary: [97821, 97210, 979210]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
97821 is a not-so-awesome number.\
97210 is an awesome number.\
979210 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (979210, 97210)\
Valid number with maximum value is 979210\
Valid number with minimum value is 97210




**Function Call2:**\
individual_line_data("976321, 321&nbsp;&nbsp;,&nbsp;&nbsp;&nbsp;9763221, &nbsp;&nbsp;&nbsp;9742, 876,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3211")\
**Output2:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
976321 is an awesome number.\
9742 is an awesome number.\
3211 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (976321, 3211)\
Valid number with maximum value is 976321\
Valid number with minimum value is 3211



**Function Call3:**\
individual_line_data("976321, 321 ,&nbsp;&nbsp;&nbsp; 9763221, 9742, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;876, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3211, 976321&nbsp;&nbsp;&nbsp;&nbsp;, 9742")\
**Output3:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
976321 is an awesome number.\
9742 is an awesome number.\
3211 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (976321, 3211)\
Valid number with maximum value is 976321\
Valid number with minimum value is 3211


In [16]:
#todo
def data_cleaning(string1):
    string2=string1.split(",")
    list1=[]
    for i in range(len(string2)):
        a=string2[i].strip(" ")
        list1.append(int(a))
    print("Data after cleaning: ",list1)
    print("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
    string1=''
    list2=[]
    list3=[]
    list4=[]

    duplicate=[]
    dict_1={}
    for i in range(len(list1)):

         if (len(str(list1[i])))>=4 and len(str(list1[i]))<=6:
             if list1[i] not in list2:
                 list2.append(list1[i])
         else:
             if list1[i] not in list3:
                list3.append(list1[i])
    for i in range(len(list2)):
        dict_1["valid"]=list2
    for j in range(len(list3)):
        dict_1["unvalid"]=list3
    # list1=[97821, 1, 97210, 963, 979210]


    for i in list1:
        if i not in list4:
            list4.append(i)
    for j in list4:
        counter=0
        for k in list1:
            if j==k:
                counter+=1
        if counter>=2:
            duplicate.append(j)

    for i in duplicate:
        dict_1["duplicate"]=duplicate
        
    print("Data dictionary printing inside the function:")
    print(dict_1)
    print("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
    print("Returned dictionary:",dict_1)
    max_val=None
    min_val=None
    for i in range(len(list1)):
        if max_val==None and min_val==None:
            min_val=list1[i]
            max_val=list1[i]
        else:
            if max_val<list1[i]:
                max_val=list1[i]
            elif min_val>list1[i]:
                min_val=list1[i]
    return max_val,min_val
    for i in range(len(string1)):
#         var1=check_awesomeness(string1[i])
        count=0
        #flag= True
        num=str(number)
        for i in range(len(num)-1):
            if int(num[i])>int(num[i+1]):
                pass
            else:
                count+=1
                #flag = False
        if count>=1:
            return False
        else:
            return True
        if var1==True:
            print(string1[i],"is an awesome number.")
        else:
            print(string1[i],"is a not-so-awesome number.")
            
    
string1="976321, 321  ,   9763221,    9742, 876,        3211"
print(data_cleaning(string1))

Data after cleaning:  [976321, 321, 9763221, 9742, 876, 3211]
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Data dictionary printing inside the function:
{'valid': [976321, 9742, 3211], 'unvalid': [321, 9763221, 876]}
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Returned dictionary: {'valid': [976321, 9742, 3211], 'unvalid': [321, 9763221, 876]}
(9763221, 321)


### Task 7
Write a function called **number_analysis** that takes a list of strings as an argument and 
analyse those strings. \
**<font color='red'>Must reuse the individual_line_data() function.</font>**

In [ ]:
#todo

### Task 8
Run the following block of code for seeing the final output of this Problem.

**Output:**
######### Printing data for line no: 01 #########\
Data after cleaning: [321, 976322]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976322], 'invalid': [321], 'duplicate': []}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976322], 'invalid': [321], 'duplicate': []}\
Valid number list obtained from the dictionary: [976322]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
976322 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (976322, 976322)\
Valid number with maximum value is 976322\
Valid number with minimum value is 976322

&emsp; 

######### Printing data for line no: 02 #########\
Data after cleaning: [97821, 1, 97210, 963, 979210, 979210]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
Valid number list obtained from the dictionary: [97821, 97210, 979210]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
97821 is a not-so-awesome number.\
97210 is an awesome number.\
979210 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (979210, 97210)\
Valid number with maximum value is 979210\
Valid number with minimum value is 97210

&emsp; 

######### Printing data for line no: 03 #########\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
976321 is an awesome number.\
9742 is an awesome number.\
3211 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (976321, 3211)\
Valid number with maximum value is 976321\
Valid number with minimum value is 3211

&emsp;

######### Printing data for line no: 04 #########\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
976321 is an awesome number.\
9742 is an awesome number.\
3211 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (976321, 3211)\
Valid number with maximum value is 976321\
Valid number with minimum value is 3211