# PRACTICE PROBLEMS ON STRING & LIST


**<font color='red'>[MUST MAINTAIN VARIABLE NAMING CONVENTIONS FOR ALL THE TASKS]</font>**
**<font color='red'>[Solve all the tasks sequentially]</font>**


### Task 1
Write a python program that will take a number as an input and check whether the number is Awesome or not. If the number is Awesome, it prints True. Otherwise False.

**Awesome number**: a number where every digit is less than its immediate left digit is called an Awesome number. A single-digit number cannot be an awesome number(e.g. 5421 is an Awesome number.)

==========================================================

**Sample Input1:**\
976321\
**Sample Output1:**\
True

==========================================================

**Sample Input2:**\
9766321\
**Sample Output2:**\
False

==========================================================

**Sample Input3:**\
9\
**Sample Output3:**\
False

==========================================================

**Sample Input4:**\
78\
**Sample Output4:**\
False

==========================================================

**Sample Input5:**\
87\
**Sample Output4:**\
True


In [7]:
#TODO
num=input("Enter the number: ")
number=int(num)
flag=False

for i in range(len(num)-1):
    if num[i]>num[i-1]:
        flag=True
    else:
        flag=False
print(flag)

Enter the number: 9766321
False


### Task 2

Write a python program that will take a number a list of numbers(integer) as an input from the user and print whether the number is Awesome or not. 

==========================================================

**Sample Input1:**\
[976321, 321, 9763221, 9742, 876, 3211]\
**Sample Output1:**\
976321 is an awesome number.\
321 is an awesome number.\
9763221 is a not-so-awesome number.\
9742 is an awesome number.\
876 is an awesome number.\
3211 is a not-so-awesome number.

==========================================================

**Sample Input2:**\
[97821, 97210, 979210]\
**Sample Output2:**\
97821 is a not-so-awesome number.\
97210 is an awesome number.\
979210 is a not-so-awesome number.


In [9]:
#TODO
list = [i for i in input()[1:-1].split(', ')]
#list =[976321, 321, 9763221, 9742, 876, 3211]
#max = list[0]
flag = False
for j in list:
    for i in range(len(j)-1):
#         list[i]=int(list[i])
        if int(j[i])>int(j[i+1]):
            flag=True
            pass
        else:
            flag=False
            break
    if flag == True:
        print(j, 'is an awesome number')
    else:
        print(j, 'is not so awesome number')

976321, 321, 9763221, 9742, 876, 3211
76321 is an awesome number
321 is an awesome number
9763221 is not so awesome number
9742 is an awesome number
876 is an awesome number
321 is an awesome number


### Task 3


Write a python program that will take a string as input from the user where each number is separated by a comma. Then gets the numbers from the given string and removes all extra spaces. Stores the clean numbers in a list and prints it.

**Hints:** For obtaining the numbers from the string, use split(). For cleaning the data, use strip().

==========================================================

**Sample Input1:**\
"97821, 1 &nbsp;&nbsp;&nbsp;  , 97210,&nbsp;&nbsp; 963, &nbsp;&nbsp;&nbsp;979210 , 979210 "\
**Sample Output1:**\
Data after cleaning: [97821, 1, 97210, 963, 979210, 979210]

==========================================================

**Sample Input2:**\
"976321, 321&nbsp;&nbsp;,&nbsp;&nbsp;&nbsp;9763221, &nbsp;&nbsp;&nbsp;9742, 876,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3211"\
**Sample Output2:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211]

==========================================================

**Sample Input3:**\
"976321, 321 ,&nbsp;&nbsp;&nbsp; 9763221, 9742, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;876, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3211, 976321&nbsp;&nbsp;&nbsp;&nbsp;, 9742"\
**Sample Output3:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]


In [1]:
list = [i for i in input()[1:-1].split(',')]
print(list)
# list_2=[]
# for i in range(len(list)):
#     a = list[i].strip()
#     list_2.append(int(a))
# print(list_2)

"97821, 1     , 97210,   963,    979210 , 979210 "
['97821', ' 1     ', ' 97210', '   963', '    979210 ', ' 979210 ']


In [1]:
# another process
string=input("Enter the string: ")[1:-1].split(",")
list=[]
for i in range(len(string)):
    a=string[i].strip(" ")
    list.append(a)
print(list)

Enter the string: "976321, 321  ,   9763221,    9742, 876,        3211"
['976321', '321', '9763221', '9742', '876', '3211']


"97821, 1     , 97210,   963,    979210 , 979210 "
97821, 1     , 97210,   963,    979210 , 979210 


### Task 4

Write a python program that will take a list of numbers(integer) as an input from the user and does the following.
* counts the number of valid, invalid, and duplicate numbers and prints these to the user.
* stores the valid and invalid numbers in a list format and prints these to the user. You need to make sure that a number is stored only Once. **Valid numbers:** A number with a minimum length of 4 and a maximum length of 6 is considered to be valid for this assignment.
* Calculate and print the percentage of valid numbers, invalid numbers, and duplicate numbers to the user. 


**Hints:** Use membership operator in and not in for checking the duplicates. For calculating the percentage, count the numbers of a particular number type.

==================================================


**Sample Input1:**\
[97821, 1, 97210, 963, 979210, 979210]\
**Sample Output1:**\
================================================\
Total numbers present in the given string: 6\
Valid number count: 3\
Valid numbers in list: [97821, 97210, 979210]\
Invalid number count: 2\
Invalid numbers in list: [1, 963]\
Duplicate number count: 1\
================================================\
Valid number percentage(%): 50.0\
Invalid number percentage(%): 33.333333333333336\
Duplicate number percentage(%): 16.666666666666668\
================================================\


**Sample Input2:**\
[976321, 321, 9763221, 9742, 876, 3211]\
**Sample Output2:**\
================================================\
Total numbers present in the given string: 6\
Valid number count: 3\
Valid numbers in list: [976321, 9742, 3211]\
Invalid number count: 3\
Invalid numbers in list: [321, 9763221, 876]\
Duplicate number count: 0\
================================================\
Valid number percentage(%): 50.0\
Invalid number percentage(%): 50.0\
Duplicate number percentage(%): 0.0\
================================================\

**Sample Input3:**\
[976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]\
**Sample Output3:**\
================================================\
Total numbers present in the given string: 8\
Valid number count: 3\
Valid numbers in list: [976321, 9742, 3211]\
Invalid number count: 3\
Invalid numbers in list: [321, 9763221, 876]\
Duplicate number count: 2\
================================================\
Valid number percentage(%): 37.5\
Invalid number percentage(%): 37.5\
Duplicate number percentage(%): 25.0\
================================================\


In [ ]:
#TODO

### Task 5

Write a python program that will take a list of numbers(integer) as an input from the user. Then stores the valid numbers, the sum of digits, and multiplication of the digits for each valid number in a list where each number is the 1st element of the list, the sum of digits is the 2nd element of the list and the multiplication of digits is the 3rd element of the list. Finally, print the nested list to the user. 

**Sample Input1:**\
[97821, 97210, 979210]\
**Sample Output1:**\
Data [number, sum of digits, product of digits]: [[97821, 27, 1008], [97210, 19, 0], [979210, 28, 0]]

================================================

**Sample Input2:**\
[976321, 9742, 3211, 30987]\
**Sample Output2:**\
Data [number, sum of digits, product of digits]: [[976321, 28, 2268], [9742, 22, 504], [3211, 7, 6], [30987, 27, 0]]

================================================

**Sample Input3:**\
[976321, 9640, 3211]\
**Sample Output3:**\
Data [number, sum of digits, product of digits]: [[976321, 28, 2268], [9640, 19, 0], [3211, 7, 6]]

================================================


### Task 6 (Merger of Task1-Task5)

Write a python program that will take a string as input from the user where each number is separated by a comma. The numbers must have a minimum length of 4 and a maximum length of 6 to be considered valid for this assignment. Then, you need to complete the following. 

* Part1: get the numbers from the given string, remove all extra spaces. (clean the data). Print the clean data to the user.
* Part2:count the number of valid, invalid, and duplicate numbers and print these to the user.
* Part3: store the valid and invalid numbers in a list format and print these to the user. You need to make sure that a number is stored only Once.
* Part4: Calculate and print the percentage of valid numbers, invalid numbers, and duplicate numbers to the user.
* Part5:store the valid numbers, the sum of digits, and multiplication of the digits for each valid number in a list where each number is the 1st element of the list, the sum of digits is the 2nd element of the list and the multiplication of digits is the 3rd element of the list. Finally, print the nested list to the user. 
* Part6: Check whether the valid numbers are Awesome or not. **Awesome number:** a number where every digit is less than its immediate left digit is called is an awesome number. (e.g. 5421 is an awesome number).

==============================================================================================

**Sample Input1:**\
"97821, 1 &nbsp;&nbsp;&nbsp;  , 97210,&nbsp;&nbsp; 963, &nbsp;&nbsp;&nbsp;979210 , 979210 "\
**Sample Output1:**\
Data after cleaning: [97821, 1, 97210, 963, 979210, 979210]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
================================================\
Total numbers present in the given string: 6\
Valid number count: 3\
Valid numbers in list: [97821, 97210, 979210]\
Invalid number count: 2\
Invalid numbers in list: [1, 963]\
Duplicate number count: 1\
================================================\
Valid number percentage(%): 50.0\
Invalid number percentage(%): 33.333333333333336\
Duplicate number percentage(%): 16.666666666666668\
================================================\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data of valid numbers:\
[number, sum of digits, product of digits]:\
[[976321, 28, 2268], [9640, 19, 0], [3211, 7, 6]]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
^_^ Awesomeness checking of the Valid numbers ^_^\
976321 is an awesome number.\
9640 is an awesome number.\
3211 is a not-so-awesome number.\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

==============================================================================================


**Sample Input2:**\
"976321, 321&nbsp;&nbsp;,&nbsp;&nbsp;&nbsp;9763221, &nbsp;&nbsp;&nbsp;9742, 876,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3211"\
**Sample Output2:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
================================================\
Total numbers present in the given string: 6\
Valid number count: 3\
Valid numbers in list: [976321, 9742, 3211]\
Invalid number count: 3\
Invalid numbers in list: [321, 9763221, 876]\
Duplicate number count: 0\
================================================\
Valid number percentage(%): 50.0\
Invalid number percentage(%): 50.0\
Duplicate number percentage(%): 0.0\
================================================\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data of valid numbers:\
[number, sum of digits, product of digits]:\
[[976321, 28, 2268], [9640, 19, 0], [3211, 7, 6]]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
^_^ Awesomeness checking of the Valid numbers ^_^\
976321 is an awesome number.\
9640 is an awesome number.\
3211 is a not-so-awesome number.\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


==============================================================================================

**Sample Input3:**\
"976321, 321 ,&nbsp;&nbsp;&nbsp; 9763221, 9742, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;876, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3211, 976321&nbsp;&nbsp;&nbsp;&nbsp;, 9742"\
**Sample Output3:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
================================================\
Total numbers present in the given string: 8\
Valid number count: 3\
Valid numbers in list: [976321, 9742, 3211]\
Invalid number count: 3\
Invalid numbers in list: [321, 9763221, 876]\
Duplicate number count: 2\
================================================\
Valid number percentage(%): 37.5\
Invalid number percentage(%): 37.5\
Duplicate number percentage(%): 25.0\
================================================\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data of valid numbers:\
[number, sum of digits, product of digits]:\
[[976321, 28, 2268], [9640, 19, 0], [3211, 7, 6]]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
^_^ Awesomeness checking of the Valid numbers ^_^\
976321 is an awesome number.\
9640 is an awesome number.\
3211 is a not-so-awesome number.\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

In [ ]:
#TODO

In [ ]:
# online practice problem 
string_1='resrasftarrtr'
string_2=string_1[0]
str3=string_1[0]
for i in range(1,len(string_1)):
    print(string_1[i])
    if string_2 == string_1[i]:
        str3+="$"
    else:
        str3+=string_1[i]

print(str3)

In [ ]:
#Write a Python program to get a single string from two given strings, separated by a space and swap the first two characters of each string
string_1='abc'
string_2="xyz"
new1=string_1[:2]+string_2[-1]
new2=string_2[:2]+string_1[-1]
swap=new2+" "+new1
print(swap)

In [ ]:
#odd string remove 
def odd_remove(string_1):
    str1=""
    for i in range(len(string_1)):
        if i%2==0:
            str1+=string_1[i]
    return str1
print(odd_remove("aninda debnath"))

In [ ]:
#Write a Python program to count the occurrences of each word in a given sentence
def odd_remove(string_1):
    string_1=string_1.split(" ")
    dict_1={}
    for i in string_1:
        if i in dict_1:
            dict_1[i]+=1
        else:
            dict_1[i]=1
    return dict_1


print(odd_remove('aninda debnath aninda how are you how going your study '))

In [1]:
#
def odd_remove(string_1):
    string_1=string_1.split(" ")
    dict_1={}
    temp=()
    list_1=[]
    list_2=[]
    for i in string_1:
        if i in dict_1:
            dict_1[i]+=1
        else:
            dict_1[i]=1
    for key,val in dict_1.items():
        list_1.append(key)
        print(list_1)
        list_2.append(val)
        print(list_2)
    return dict_1
print(odd_remove('aninda debnath aninda how are you how going your study '))

['aninda']
[2]
['aninda', 'debnath']
[2, 1]
['aninda', 'debnath', 'how']
[2, 1, 2]
['aninda', 'debnath', 'how', 'are']
[2, 1, 2, 1]
['aninda', 'debnath', 'how', 'are', 'you']
[2, 1, 2, 1, 1]
['aninda', 'debnath', 'how', 'are', 'you', 'going']
[2, 1, 2, 1, 1, 1]
['aninda', 'debnath', 'how', 'are', 'you', 'going', 'your']
[2, 1, 2, 1, 1, 1, 1]
['aninda', 'debnath', 'how', 'are', 'you', 'going', 'your', 'study']
[2, 1, 2, 1, 1, 1, 1, 1]
['aninda', 'debnath', 'how', 'are', 'you', 'going', 'your', 'study', '']
[2, 1, 2, 1, 1, 1, 1, 1, 1]
{'aninda': 2, 'debnath': 1, 'how': 2, 'are': 1, 'you': 1, 'going': 1, 'your': 1, 'study': 1, '': 1}


In [5]:
#dubble value remove 
# string_1="aabbccddeeffzyx"
# dict_1={}
# string_2=''
# for i in range(len(string_1)):
#     if string_1[i] not in dict_1:
#         dict_1[string_1[i]]=1
#     else:
#         dict_1[string_1[i]]+=1
# print(dict_1)
# # for key,val in dict_1.items():
# #      if val<2:
# #         string_2+=key
# # print(string_2)

string_1="aabbccddeeffzyx"
str1='' #abcdefzxy

str2=''#abcdef
str3=''

for i in range(len(string_1)):
    if string_1[i] not in str1:
        str1+=string_1[i]

    else:
#         if string_1[i] in str1:
            str2+=string_1[i]
print(str1)
print(str2)
for i in range(len(string_1)):
    if string_1[i] not in str2:
        str3+=string_1[i]
print(str3)

abcdefzyx
abcdef
zyx
